feat: Pearson Correlation Coefficient

diff --git a/cantril_data_cleaning b/cantril_data_cleaning
--- a/cantril_data_cleaning
+++ b/cantril_data_cleaning
@@ -2,17 +2,32 @@
 
 # Check if three file names are provided
 if [ "$#" -ne 3 ]; then
-    echo "Usage: $0 file1.tsv file2.tsv file3.tsv"
+    echo "Please use three tsv files: file1.tsv file2.tsv file3.tsv"
     exit 1
 fi
 
-file1=$1
-file2=$2
-file3=$3
+# 定义标题和文件变量
+file1=""
+file2=""
+file3=""
+
+# 循环检查每个输入文件的第一行
+for file in "$@"; do
+    header=$(head -n 1 "$file")
+    if [[ "$header" == *"Homicide rate per 100,000 population - Both sexes - All ages"* ]]; then
+        file1="$file"
+    elif [[ "$header" == *"GDP per capita, PPP (constant 2017 international $)"* ]]; then
+        file2="$file"
+    elif [[ "$header" == *"Life expectancy - Sex: all - Age: at birth - Variant: estimates"* ]]; then
+        file3="$file"
+    fi
+done
 
 # Process each file
 for file in "$file1" "$file2" "$file3"; do
 
+    echo ""
+    echo ""
     echo "Processing file: $file"
     echo "----------------------------------------"
 
@@ -22,13 +37,11 @@ for file in "$file1" "$file2" "$file3"; do
     # 检查第一行是否包含制表符
     if [[ "$first_line" =~ $'\t' ]]; then
         echo "File $file is already tab-separated."
-        echo ""
     else
         # 使用 awk 将文件转换为制表符分隔格式
         awk 'BEGIN { FS="\t"; OFS="\t" } { print }' "$file" > "${file}.tmp"
         mv "${file}.tmp" "$file"
         echo "File $file has been converted to tab-separated format."
-        echo ""
     fi
 
 
@@ -42,20 +55,14 @@ for file in "$file1" "$file2" "$file3"; do
         }
     }' "$file"
 
-    
+
     column_number=$(awk -F '\t' '{ for (i=1; i<=NF; i++) if ($i == "Continent") {print i} }' "$file")
 
     result=$(awk -F'\t' '$2 != "" { print }' "$file")
 
     result=$(awk -F'\t' 'NR == 1 || ($3 >= 2011 && $3 <= 2021)' <<< "$result")
 
-    echo "$column_number"
-
-
     if [ "$column_number" ]; then
-
-        # awk -F '\t' -v col="$column_number" 'BEGIN {FS = "\t"; OFS = "\t"} {$col = ""; sub("\t\t","\t") } 1' <<< "$result" > "${file%.tsv}_processed.tsv"
-        # awk -F '\t' -v col="$column_number" 'BEGIN {FS = "\t"; OFS = "\t"} {$col = ""; sub("\t\t","\t") } 1' "$file" > tmpfile && mv tmpfile "$file"
     
         awk -F '\t' -v col="$column_number" 'BEGIN {FS = "\t"; OFS = "\t"} {
             if(NF >= col) {  # Check if the number of fields is greater than or equal to the column number
@@ -65,50 +72,14 @@ for file in "$file1" "$file2" "$file3"; do
                 print $0 > "/dev/stderr"
             }
         } 1' <<< "$result" > tmpfile && mv tmpfile "$file"
-
         echo "Column Continent has been removed from the file."
-
+        echo ""
     else
-
         echo "$result" > "$file"
         echo "No column removed from the file."
-
+        echo ""
     fi
-
-    echo ""
 done
-
-# 获取每个文件的行数
-lines_file1=$(wc -l < "$file1")
-lines_file2=$(wc -l < "$file2")
-lines_file3=$(wc -l < "$file3")
-
-# 用数组存储文件名和对应的行数
-files=("$file1" "$file2" "$file3")
-lines=("$lines_file1" "$lines_file2" "$lines_file3")
-
-# 对行数进行降序排列
-for ((i=0; i<${#lines[@]}; i++)); do
-    for ((j=$i+1; j<${#lines[@]}; j++)); do
-        if [[ ${lines[$i]} -lt ${lines[$j]} ]]; then
-            temp=${lines[$i]}
-            lines[$i]=${lines[$j]}
-            lines[$j]=$temp
-            temp=${files[$i]}
-            files[$i]=${files[$j]}
-            files[$j]=$temp
-        fi
-    done
-done
-
-# 将排序后的文件名传给变量
-max_file=${files[0]}
-second_file=${files[1]}
-third_file=${files[2]}
-
-echo "最多行数的文件是：$max_file"
-echo "第二多行数的文件是：$second_file"
-echo "第三多行数的文件是：$third_file"
 
 
 awk 'BEGIN {FS=OFS="\t"}
@@ -121,7 +92,7 @@ awk 'BEGIN {FS=OFS="\t"}
         } else {
             print $0
         }
-    }' $third_file $second_file $max_file > output.tsv # Redirect output to output.tsv
+    }' $file1 $file2 $file3 > output.tsv # Redirect output to output.tsv
 
 
 # Set field separator (FS) and output field separator (OFS) as tab, and print column headers.
@@ -133,9 +104,27 @@ awk 'BEGIN {
 # Print specified columns in the desired order.
 NR > 1 {
     print $1, $2, $3, $12, $6, $18, $4, $5
-}' output.tsv > cleaned.tsv  # Redirect output to cleaned.tsv
+}' output.tsv | tee cleaned.tsv  # Redirect output to cleaned.tsv
 
-# rm output.tsv
+# Check the exit status of the awk command
+if [ $? -eq 0 ]; then
+    # Check if cleaned.tsv file exists and is not empty
+    if [ -s cleaned.tsv ]; then
+        echo "cleaned.tsv file has been generated and contains data."
+        echo ""
+        echo ""
+    else
+        echo "cleaned.tsv file is empty or not generated."
+        echo ""
+        echo ""
+    fi
+else
+    echo "Command execution failed."
+    echo ""
+    echo ""
+fi
+
+rm output.tsv
 
 
 
